name: Test
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test-check:
    name: runner / hadolint (github-check)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: ./
        with:
          reporter: github-check
          level: info
          exclude: Dockerfile.dockerignore

  test-pr-review:
    if: github.event_name == 'pull_request'
    name: runner / hadolint (github-pr-review)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: reviewdog/action-hadolint@v1
        with:
          fail_level: error
          filter_mode: diff_context
          exclude: Dockerfile.dockerignore
