name: Test
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test-check:
    name: runner / hadolint (github-check)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
      - uses: ./
        with:
          reporter: github-check
          level: info
          exclude: Dockerfile.dockerignore

  test-pr-review:
    if: github.event_name == 'pull_request'
    name: runner / hadolint (github-pr-review)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
      - uses: ./
        with:
          reporter: github-pr-review
          filter_mode: diff_context
          exclude: Dockerfile.dockerignore
